name: build_pat

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'README_zh-CN.md'
      - 'docs/**'
      - 'examples/**'
      - '.dev_scripts/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  MMCV_WITH_OPS: 1

jobs:
  build_parrots:
    runs-on: ubuntu-18.04
    container:
      image: ghcr.io/zhouzaida/parrots:pat_latest_ci
      credentials:
        username: zhouzaida
        password: ${{ secrets.PARROTS_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - name: Build and test
        run: |
          source /usr/local/env/pat_latest
          pip install -r requirements/test.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
          MMCV_WITH_OPS=1 pip install -e . -v -i https://pypi.tuna.tsinghua.edu.cn/simple
          pytest tests/
