name: build_pat

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  MMCV_WITH_OPS: 1

jobs:
  build_parrots:
    runs-on: ubuntu-18.04
    container:
      image: ghcr.io/zhouzaida/parrots20220307:latest
      credentials:
        username: zhouzaida
        password: ${{ secrets.CR_PAT }}

    steps:
      - uses: actions/checkout@v2
      - name: Install unittest dependencies
        run: pip install -r requirements/test.txt
      - name: Build and install
        run: rm -rf .eggs && MMCV_WITH_OPS=1 pip install -e .
      - name: Test
          coverage run --branch --source=mmcv -m pytest tests/
          coverage xml
          coverage report -m
